package app

import com.amazonaws.services.dynamodbv2.datamodeling.*

@DynamoDBTable(tableName="cardinal_challenge")
@ToString(includeNames=true, includeFields=true)
class ChallengeBean {

    @DynamoDBHashKey
    Long accountId // Hash key
    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    String id // Range key, with an automatically generated ID

    @DynamoDBAttribute
    int count = 0
    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(localSecondaryIndexName="creationDate")
    Date creationDate
    @DynamoDBAttribute
    String message
    @DynamoDBAttribute
    String title

}
